<a href="https://colab.research.google.com/github/samri-Aa/final-project/blob/main/final%20project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

columns = [
    "Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
    "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"
]

df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace invalid 0 values with NaN (medical data cannot be 0)
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

df[cols] = df[cols].replace(0, np.nan)

# Fill missing values with median
df.fillna(df.median(), inplace=True)

# Check if any missing values remain
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Medical datasets often contain invalid zero values. These were replaced with NaN and then filled using median values to ensure accurate statistical analysis.

In [4]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.128213,0.208615,0.081770,0.025047,0.021559,-0.033523,0.544341,0.221898
Glucose,0.128213,1.000000,0.218937,0.192615,0.419451,0.231049,0.137327,0.266909,0.492782
BloodPressure,0.208615,0.218937,1.000000,0.191892,0.045363,0.281257,-0.002378,0.324915,0.165723
SkinThickness,0.081770,0.192615,0.191892,1.000000,0.155610,0.543205,0.102188,0.126107,0.214873
Insulin,0.025047,0.419451,0.045363,0.155610,1.000000,0.180241,0.126503,0.097101,0.203790
BMI,0.021559,0.231049,0.281257,0.543205,0.180241,1.000000,0.153438,0.025597,0.312038
DiabetesPedigreeFunction,-0.033523,0.137327,-0.002378,0.102188,0.126503,0.153438,1.000000,0.033561,0.173844
Age,0.544341,0.266909,0.324915,0.126107,0.097101,0.025597,0.033561,1.000000,0.238356
Outcome,0.221898,0.492782,0.165723,0.214873,0.203790,0.312038,0.173844,0.238356,1.000000

Correlation analysis was used to understand relationships between variables. The results show that Glucose and BMI have stronger positive relationships with diabetes outcome compared to other features. This suggests they are important predictors of diabetes risk.

In [5]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[20,30,40,50,60,100],
    labels=["20-30","30-40","40-50","50-60","60+"]
)

pd.crosstab(df["AgeGroup"], df["Outcome"])

Outcome     0   1
AgeGroup
20-30     327  90
30-40      81  76
40-50      49  64
50-60      23  31
60+        20   7

A crosstab analysis was performed to examine the relationship between age groups and diabetes outcome. The results indicate that diabetes cases increase in older age groups, especially above 40 years. This suggests age is an important risk factor for diabetes.

In [6]:
df["BMI_Category"] = pd.cut(
    df["BMI"],
    bins=[0,18.5,25,30,100],
    labels=["Underweight","Normal","Overweight","Obese"]
)

pd.crosstab(df["BMI_Category"], df["Outcome"])

Outcome         0    1
BMI_Category
Underweight     4    0
Normal        101    7
Overweight    136   44
Obese         259  217

BMI was grouped into categories to analyze its effect on diabetes. The results show that overweight and obese individuals have a higher number of diabetes cases. This indicates that higher body weight is strongly associated with increased diabetes risk.

# ***conclusion***
This analysis explored the relationship between health indicators and diabetes using the Pima Indians Diabetes dataset. The study showed that glucose level, BMI, and age are the most significant factors associated with diabetes. Older individuals and those with higher BMI values showed a greater likelihood of diabetes. Correlation and grouping analysis confirmed that lifestyle and metabolic factors play an important role in diabetes risk prediction. This demonstrates how data analysis can be used to identify health risks and support early detection.